### ISSUE TITLE
Inegration with the webpack dev server

### ISSUE THREAD

**Issue by armandabric** [idiotWu/sw-loader#1]
I'm in the use case you have resolve in this issue https://github.com/service-mocker/service-mocker/issues/16: I use service-mocker with CRA and this plugin. 

This works file 👍  The only down side is that when I modify the `server.js` the webpack dev server does not rebuild the service worker. I have to manually restart the server.

Could you make this loader compatible with the webpack dev server?

```
// FakeApi/client.js

// eslint-disable-next-line import/no-webpack-loader-syntax
import publicSwPath from 'sw-loader?name=sw-fake-api.js!./server.js';
import { createClient } from 'service-mocker/client'

// We only import the server to have webpack rebuild the bundle and the
// service-worker in dev environment
import './server';

export default () => createClient(publicSwPath);
```

**Comment by dolphin-wood** [comment]
It was just solved in v0.1.1, see service-mocker/service-mocker#36 :)

**Comment by caesarsol** [comment]
@Spy-Seth I'm using [this code](https://github.com/service-mocker/service-mocker/issues/36#issuecomment-319986872) to make the SW auto-refresh in background, you may find it interesting!

**Comment by armandabric** [comment]
Ho perfect 👍
