### ISSUE TITLE
missing peer depency for webpack 3 breaks npm shrinwrap

### ISSUE THREAD

**Issue by BogdanDumitruMarian** [idiotWu/sw-loader#2]
Hello,

As decribed in the title, the missing dependency for webpack '^3.x.x' will cause npm shrinkwrap to fail.
Whether shrinkwrap should ignore/warn on/fail because of missing peer dependencies or not is, of course, a different topic.
Apart from that, I can confirm sw-loader works with webpack3 as well :)

Best regards,
Bogdan

**Comment by dolphin-wood** [comment]
Thanks for reporting! Will fix it soon.

**Comment by dolphin-wood** [comment]
Fixed in 0.1.2
